common/models/Profile.php
<?php
namespace common\models;

use Yii;
use yii\db\Expression;
use yii\helpers\Html;

/**
 * This is the model class for table "{{%profile}}".
 *
 * @property int $user_id
 * @property string $last_name
 * @property string $first_name
 * @property string $middle_name
 * @property string $photo
 * @property string $timezone
 * @property int $gender_id
 * @property int $timezone_offset
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 *
 * @property User $user
 */
class Profile extends \yii\db\ActiveRecord
{
    const GENDER_M = 1;
    const GENDER_G = 2;

    private $_genders = [
        self::GENDER_M => 'М',
        self::GENDER_G => 'Ж',
    ];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%profile}}';
    }

    public function behaviors()
    {
        return [
            [
                'class' => 'yii\behaviors\TimestampBehavior',
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'last_name', 'first_name', 'middle_name', 'timezone', 'timezone_offset', 'created_at'], 'safe'],
            [['user_id', 'timezone_offset', 'status_id', 'gender_id'], 'integer'],
            [['last_name', 'first_name', 'middle_name', 'photo'], 'string', 'max' => 255],
            [['timezone'], 'string', 'max' => 24],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('user', 'User ID'),
            'last_name' => Yii::t('user', 'Last Name'),
            'first_name' => Yii::t('user', 'First Name'),
            'middle_name' => Yii::t('user', 'Middle Name'),
            'photo' => Yii::t('user', 'Photo'),
            'gender_id' => Yii::t('user', 'Gender ID'),
            'timezone' => Yii::t('user', 'Timezone'),
            'timezone_offset' => Yii::t('user', 'Timezone Offset'),
            'status_id' => Yii::t('user', 'Status ID'),
            'created_at' => Yii::t('user', 'Created At'),
            'fullName' => Yii::t('user', 'Full Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function getUrl()
    {
        return ['/site/user', 'id' => $this->user_id];
    }

    public function getFullName($withLinkProfile = false)
    {
        $fullname = trim(preg_replace('/\s+/siu', ' ', $this->last_name . ' ' . $this->first_name . ' ' . $this->middle_name));

        return ($withLinkProfile) ? Html::a($fullname, $this->getUrl(), ['target' => '_blank']) : $fullname;
    }

    public function getFullNameCard($withLinkProfile = false)
    {
        return '[' . $this->user_id . '] ' . $this->getFullName($withLinkProfile);
    }

    public static function primaryKey()
    {
        return ['user_id'];
    }

    public function getGenders()
    {
        return $this->_genders;
    }

    public function getGender($id=0)
    {
        if (!$id) $id = Profile::GENDER_M;
        return ((!empty($this->_genders[$id])) ? $this->_genders[$id] : 'Не указано');
    }
}

common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\db\Query;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{

    public $password = null;

    const ROLE_ADMIN = 'admin';
    const ROLE_REGISTERED = 'user';
    const ROLE_GUEST = 'guest';

    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    private $_isAdmin = null;

    private $_statuses = [
        self::STATUS_ACTIVE => 'Активна',
        self::STATUS_DELETED => 'Удалена',
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\behaviors\TimestampBehavior',
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at','password'], 'safe'],
            [['email'], 'required'],
            [['email'], 'email'],
            [['email'], 'unique'],
            [['phone'], 'number'],
            ['status_id', 'default', 'value' => self::STATUS_ACTIVE],
            ['status_id', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            [['username','password'], 'string', 'max' => 255],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('user', 'ID'),
            'created_at' => Yii::t('user', 'Created At'),
            'password_hash' => Yii::t('user', 'Password Hash'),
            'email' => Yii::t('user', 'Email'),
            'phone' => Yii::t('user', 'Phone'),
            'status_id' => Yii::t('user', 'Status ID'),
            'password' => Yii::t('user', 'Password'),
            'status' => Yii::t('user', 'Status'),
        ];
    }

    static public function roleArray()
    {
        return [
            self::ROLE_ADMIN,
            self::ROLE_REGISTERED,
            self::ROLE_GUEST,
        ];
    }

    public function getRoles()
    {
        return \Yii::$app->authManager->getRolesByUser($this->id);
    }

    public function getRole()
    {
        $roles = @unserialize($this->roles);

        if (is_array($roles) && !empty($roles[0])) {
            if ($roles[0] == 'ROLE_ADMIN')
                return self::ROLE_ADMIN;
        }

        return self::ROLE_REGISTERED;
    }

    static public function getRoleOfUser($id)
    {
        if ($id == 1) return User::ROLE_ADMIN;
        else return User::ROLE_REGISTERED;


        $roleArray = (new Query())
            ->select('roles')
            ->from(self::tableName())
            ->where(['id' => $id])
            ->scalar();

        $roles = @unserialize($roleArray);

        if (is_array($roles) && !empty($roles[0])) {
            if ($roles[0] == 'ROLE_ADMIN')
                return User::ROLE_ADMIN;
        }

        return User::ROLE_REGISTERED;
    }

    public function getIsAdmin()
    {
        if ($this->_isAdmin === null)
            $this->_isAdmin = array_key_exists(self::ROLE_ADMIN, $this->getRoles());

        return $this->_isAdmin;
    }

    public function getProfile()
    {
        return $this->hasOne(Profile::class, ['user_id' => 'id']);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status_id' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::find()->alias('u')
            ->joinWith('userTokens as tk')
            ->andWhere(['tk.bearer' => $token])
            ->andWhere('u.id = tk.user_id')
            ->one(Yii::$app->db);
    }

    /**
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status_id' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status_id' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
        return $this->password_reset_token;
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getName()
    {
        $fullname = trim($this->username);
        return $fullname;
    }

    public function getPhoneString()
    {
        if (empty($this->phone))
            return '';

        $number = preg_replace('/[^\d]+/siu', '', $this->phone);
        if (mb_strlen($number) < 10 || mb_strlen($number) > 11)
            return '';

        if (mb_strlen($number) === 10) {
            $number = '7' . $number;
        }

        $number = preg_replace('/^8/siu', '7', $number);

        return '+' . $number;
    }

    public function getStatuses()
    {
        return $this->_statuses;
    }

    public function getStatus($id=0)
    {
        if (!$id) $id = $this->status_id;
        return ((!empty($this->_statuses[$id])) ? $this->_statuses[$id] : Yii::t('user', 'No Specify'));
    }

    public function getUserTokens()
    {
        return $this->hasMany(UserToken::class, ['user_id' => 'id']);
    }

    public function addUserToken($fbase = '', $fbasePlatform = 'android')
    {
        $ut = new UserToken();
        $ut->user_id = $this->id;
        $ut->bearer = $this->generatePasswordResetToken();
        $ut->push_token = $fbase;
        $ut->platform = $fbasePlatform;

        $ut->save();

        return $ut->bearer;
    }

    public function getFullName()
    {
        $text = '';
        if (defined('BACKEND') && BACKEND)
            $text = '[ ' . $this->id . ' ] ';

        if ($this->profile)
            $text .= $this->profile->fullName;

        return $text;
    }
}

backend/controllers/UserController.php
<?php
namespace backend\controllers;

use common\models\Profile;
use Yii;
use common\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\UserSearch;
/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'roles' => ['admin'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->setPassword($model->password);
            $model->generateAuthKey();
            $model->username = $model->email;

            if ($model->save()) {

                $profile = $model->profile;
                if (!$profile) $profile = new Profile();
                $profile->load(Yii::$app->request->post());
                $profile->user_id = $model->id;
                $profile->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->password) $model->setPassword($model->password);
            $model->username = $model->email;

            if ($model->save()) {

                $profile = $model->profile;
                if (!$profile) $profile = new Profile();
                $profile->load(Yii::$app->request->post());
                $profile->user_id = $model->id;
                $profile->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if ($model = $this->findModel($id)) {
            $model->status_id = User::STATUS_DELETED;
            $model->save();
        }

        return $this->redirect(['index']);
    }

    public function actionToggleAdmin($id = 0)
    {
        if ($id && $user = User::find()->andWhere(['id' => $id])->one()) {
            $auth = Yii::$app->getAuthManager();
            $admin = $auth->getRole('admin');

            $adminUsers = $auth->getUserIdsByRole($admin->name);

            if (!in_array($user->id, $adminUsers) && $user->email !== 'info@wfstudio.ru')
            {
                $auth->assign($admin, $user->id);
                Yii::$app->session->setFlash('success', 'Админ назначен');
            }
            elseif ($user->email !== 'info@wfstudio.ru')
            {
                $auth->revoke($admin, $user->id);
                Yii::$app->session->setFlash('danger', 'Админ отзван');
            }
        }

        return $this->redirect('index');
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/user/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\User;
use common\models\Profile;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */

if (!$model->status_id)
    $model->status_id = User::STATUS_ACTIVE;

$profile = $model->profile;

if (!$profile)
    $profile = new Profile();

if (!$profile->gender_id)
    $profile->gender_id = Profile::GENDER_M;
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->hiddenInput()->label(false); ?>

    <?= $form->field($model, 'status_id')->radioList($model->statuses); ?>

    <?= $form->field($profile, 'gender_id')->radioList($profile->genders); ?>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($profile, 'last_name')->textInput(); ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($profile, 'first_name')->textInput(); ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($profile, 'middle_name')->textInput(); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'email'); ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'phone')->textInput() ?>
        </div>
    </div>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('user', 'Add') : Yii::t('user', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = Yii::t('user', 'Add User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\date\DatePicker;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('user', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('user', 'Add User'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'pager' => [
            'disabledPageCssClass' => 'disabled',
            'pageCssClass' => 'page-link',
            'nextPageCssClass' => 'page-link',
            'prevPageCssClass' => 'page-link',
            'firstPageCssClass' => 'page-link',
            'lastPageCssClass' => 'page-link',
        ],
        'columns' => [
            'id',
            [
                'attribute' => 'created_at',
                'value' => 'created_at',
                'filter' => DatePicker::widget([
                    'model' => $searchModel,
                    'type' => DatePicker::TYPE_INPUT,
                    'attribute'=>'created_at',
                    'language' => 'ru',
                    'options' => ['class' => 'form-control'],
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ]),
            ],
            [
                'attribute' => 'status',
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status_id',
                    [null => Yii::t('user', 'Not chosen')] + $searchModel->getStatuses(),
                    ['class' => 'form-control']),
            ],
            [
                'attribute' => 'fullName',
                'label' => Yii::t('user', 'Full Name'),
            ],
            'email:email',
            [
                'label' => 'Role',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::a(
                        (Yii::$app->authManager->checkAccess($model->id, 'admin')?'Revoke':'Assing') . ' admin',
                        ['user/toggle-admin', 'id' => $model->id]
                    );
                }
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = Yii::t('user', 'Update User: ') . $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('user', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('user', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('user', 'Remove this user?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'created_at:datetime',
            [
                'attribute' => 'status',
                'label' => Yii::t('user', 'Status ID'),
            ],
//            'profile.timezone',
//            'profile.timezone_offset',
            [
                'attribute' => 'fullName',
                'label' => Yii::t('user', 'Full Name'),
            ],
//            'profile.photo',
            [
                'attribute' => 'profile.gender',
                'label' => Yii::t('user', 'Gender ID'),
            ],
            [
                'attribute' => 'username',
                'label' => Yii::t('user', 'User Name'),
            ],
            'email:email',
//            'auth_key',
//            'password_hash',
//            'password_reset_token',
        ],
    ]) ?>

</div>